#!/usr/bin/env bash
# ENV-05：校验 test-accounts.yaml 主测试账号已激活，并导出 Staging 冒烟/E2E 环境变量。
# 用法：
#   ./activate-staging.sh              # 打印 export 语句
#   ./activate-staging.sh --write-env   # 写入 staging.env
#   ./activate-staging.sh --check       # 仅校验，失败 exit 1
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ACCOUNTS_YAML="${SCRIPT_DIR}/test-accounts.yaml"
OUT_ENV="${SCRIPT_DIR}/staging.env"

ADMIN_PHONE="13800138001"
ADMIN_CODE="123456"
MEMBER_PHONE="13800138002"
MEMBER_CODE="123456"
DEVICE_ID="qa-device-iphone12-001"
BASE_URL="${BASE_URL:-https://staging-api-cn.example.com}"

log() { printf '[accounts] %s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

check_admin_active() {
  [[ -f "${ACCOUNTS_YAML}" ]] || die "missing ${ACCOUNTS_YAML}"
  grep -q 'id: qa-cn-admin-001' "${ACCOUNTS_YAML}" || die "qa-cn-admin-001 not found"
  if ! grep -A15 'id: qa-cn-admin-001' "${ACCOUNTS_YAML}" | grep -q 'status: active'; then
    die "qa-cn-admin-001 status must be active (ENV-05)"
  fi
  log "OK: qa-cn-admin-001 status=active"
}

emit_env() {
  cat <<EOF
# Generated by tests/accounts/activate-staging.sh — do not commit secrets
# Source: test-accounts.yaml (qa-cn-admin-001 active)
BASE_URL=${BASE_URL}
STAGING_RESOLVE=${STAGING_RESOLVE:-}

SMOKE_REGION=cn
SMOKE_APP_VERSION=1.0.0-staging
SMOKE_DEVICE_ID=${DEVICE_ID}
SMOKE_PHONE=${ADMIN_PHONE}
SMOKE_CODE=${ADMIN_CODE}

E2E_REGION=cn
E2E_APP_VERSION=1.0.0-staging
E2E_DEVICE_ID=${DEVICE_ID}
E2E_ADMIN_PHONE=${ADMIN_PHONE}
E2E_ADMIN_CODE=${ADMIN_CODE}
E2E_MEMBER_PHONE=${MEMBER_PHONE}
E2E_MEMBER_CODE=${MEMBER_CODE}

# auth-family-svc Staging Deployment 需设置：
# MOCK_SMS_FIXED_CODE=${ADMIN_CODE}
EOF
}

print_exports() {
  emit_env | grep -v '^#' | grep -v '^$' | while IFS='=' read -r key value; do
    printf 'export %s=%q\n' "${key}" "${value}"
  done
  echo
  log "Staging SMS: set MOCK_SMS_FIXED_CODE=${ADMIN_CODE} on auth-family-svc"
  log "See tests/accounts/README.md §3"
}

MODE="${1:-}"

check_admin_active

case "${MODE}" in
  --check)
    log "check passed"
    ;;
  --write-env)
    emit_env > "${OUT_ENV}"
    log "wrote ${OUT_ENV}"
    ;;
  --help|-h)
    sed -n '2,6p' "$0"
    ;;
  *)
    print_exports
    ;;
esac
